# Generated by Django 4.1.4 on 2022-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_post_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(max_length=9)),
                ('site_description', models.TextField(blank=True, max_length=400, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dashboards/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
